### ISSUE TITLE
"Work in progress."?

### ISSUE THREAD

**Issue by Zomis** [FasterXML/jackson-module-swagger#13]
Latest commit e1ed056 on 27 Feb 2015

This was more than two years ago. Is this still considered "Work in progress" or is this dead?

Or is it just the README that needs to be updated?

Which versions of Swagger is supported?

**Comment by fehguy** [comment]
I believe this logic was moved to [swagger-core](github.com/swagger-api/swagger-core)

**Comment by Zomis** [comment]
So this project is deprecated? In that case, please mention that in README.md.

**Comment by cowtowncoder** [comment]
Wull do, thanks.
